USE [master]
GO

/****** Object:  Database [Imdb]    Script Date: 3/20/2022 10:10:37 PM ******/
CREATE DATABASE [Imdb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Imdb', FILENAME = N'C:\MSSQL2019\MSSQL15.TESTER2019\MSSQL\DATA\Imdb.mdf' , SIZE = 10000000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 
 LOG ON 
( NAME = N'Imdb_log', FILENAME = N'e:\MSSQL2019\MSSQL15.TESTER2019\MSSQL\Data\Imdb_log.ldf' , SIZE = 102400KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Imdb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Imdb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Imdb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Imdb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Imdb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Imdb] SET ARITHABORT OFF 
GO

ALTER DATABASE [Imdb] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Imdb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Imdb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Imdb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Imdb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Imdb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Imdb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Imdb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Imdb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Imdb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Imdb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Imdb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Imdb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Imdb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Imdb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Imdb] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [Imdb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Imdb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Imdb] SET  MULTI_USER 
GO

ALTER DATABASE [Imdb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Imdb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Imdb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Imdb] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Imdb] SET DELAYED_DURABILITY = FORCED 
GO

ALTER DATABASE [Imdb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [Imdb] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Imdb] SET  READ_WRITE 
GO


