
CREATE TABLE [Imdb].[Profession](
	[ProfessionName] [varchar](100) NOT NULL,
 CONSTRAINT [PKProfession] PRIMARY KEY CLUSTERED 
(
	[ProfessionName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
)
AS NODE  WITH (DATA_COMPRESSION = PAGE)
GO
