USE [master]
GO

/****** Object:  Database [ImdbRelational]    Script Date: 3/20/2022 10:10:37 PM ******/
CREATE DATABASE [ImdbRelational]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ImdbRelational', FILENAME = N'C:\MSSQL2019\MSSQL15.TESTER2019\MSSQL\DATA\ImdbRelational.mdf' , SIZE = 10000000KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 
 LOG ON 
( NAME = N'ImdbRelational_log', FILENAME = N'e:\MSSQL2019\MSSQL15.TESTER2019\MSSQL\Data\ImdbRelational_log.ldf' , SIZE = 102400KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ImdbRelational].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [ImdbRelational] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [ImdbRelational] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [ImdbRelational] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [ImdbRelational] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [ImdbRelational] SET ARITHABORT OFF 
GO

ALTER DATABASE [ImdbRelational] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [ImdbRelational] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [ImdbRelational] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [ImdbRelational] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [ImdbRelational] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [ImdbRelational] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [ImdbRelational] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [ImdbRelational] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [ImdbRelational] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [ImdbRelational] SET  DISABLE_BROKER 
GO

ALTER DATABASE [ImdbRelational] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [ImdbRelational] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [ImdbRelational] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [ImdbRelational] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [ImdbRelational] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [ImdbRelational] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [ImdbRelational] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [ImdbRelational] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [ImdbRelational] SET  MULTI_USER 
GO

ALTER DATABASE [ImdbRelational] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [ImdbRelational] SET DB_CHAINING OFF 
GO

ALTER DATABASE [ImdbRelational] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [ImdbRelational] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [ImdbRelational] SET DELAYED_DURABILITY = FORCED 
GO

ALTER DATABASE [ImdbRelational] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [ImdbRelational] SET QUERY_STORE = OFF
GO

ALTER DATABASE [ImdbRelational] SET  READ_WRITE 
GO


