

/****** Object:  Table [Imdb].[EpisodeOf]    Script Date: 3/3/2021 6:25:30 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [Imdb].[EpisodeOf](
	FromId INT NOT null,
	ToId INT NOT null,
	[SeasonNumber] [int] NOT NULL,
	[EpisodeNumber] [int] NOT NULL,
 CONSTRAINT [PKEpisodeOf] PRIMARY KEY
(
	FromId, ToId
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
)
 WITH (DATA_COMPRESSION = PAGE)
GO