USE ImdbRelational
GO
/****** Object:  Table [Imdb].[Genre]    Script Date: 3/3/2021 6:25:30 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

DROP TABLE IF EXISTS Imdb.Genre
GO

CREATE TABLE [Imdb].[Genre](
	GenreId INT IDENTITY NOT NULL CONSTRAINT PKGenre PRIMARY KEY,
	[GenreName] [VARCHAR](100) NOT NULL,
 CONSTRAINT [AKGenre] UNIQUE
(
	[GenreName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
)
WITH (DATA_COMPRESSION = PAGE)
GO
