
/****** Object:  Table [Imdb].[TitleEpisode]    Script Date: 3/3/2021 6:25:30 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

DROP TABLE IF EXISTS Imdb.TitleEpisode
GO

CREATE TABLE [Imdb].[TitleEpisode](
	TitleEpisodeId INT IDENTITY CONSTRAINT PKTitleEpisode PRIMARY KEY,
	[TitleNumber] [varchar](10) NOT NULL,
	[SeasonNumber] [int] NOT NULL,
	[EpisodeNumber] [int] NOT NULL,
 CONSTRAINT [AKTitleEpisode] UNIQUE
(
	[TitleNumber] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
)
WITH (DATA_COMPRESSION = PAGE)
GO