
CREATE DATABASE [IMDBStaging]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'IMDBStaging', FILENAME = N'C:\MSSQL2019\MSSQL15.TESTER2019\MSSQL\DATA\IMDBStaging.mdf' , SIZE = 307200KB , FILEGROWTH = 10%)
 LOG ON 
( NAME = N'IMDBStaging_log', FILENAME = N'e:\MSSQL2019\MSSQL15.TESTER2019\MSSQL\Data\IMDBStaging_log.ldf' , SIZE = 102400KB , FILEGROWTH = 10%)
GO
ALTER DATABASE [IMDBStaging] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [IMDBStaging] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [IMDBStaging] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [IMDBStaging] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [IMDBStaging] SET ARITHABORT OFF 
GO
ALTER DATABASE [IMDBStaging] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [IMDBStaging] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [IMDBStaging] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [IMDBStaging] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [IMDBStaging] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [IMDBStaging] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [IMDBStaging] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [IMDBStaging] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [IMDBStaging] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [IMDBStaging] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [IMDBStaging] SET  DISABLE_BROKER 
GO
ALTER DATABASE [IMDBStaging] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [IMDBStaging] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [IMDBStaging] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [IMDBStaging] SET READ_COMMITTED_SNAPSHOT ON 
GO
ALTER DATABASE [IMDBStaging] SET  READ_WRITE 
GO
ALTER DATABASE [IMDBStaging] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [IMDBStaging] SET  MULTI_USER 
GO
ALTER DATABASE [IMDBStaging] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [IMDBStaging] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO
ALTER DATABASE [IMDBStaging] SET DELAYED_DURABILITY = FORCED 
GO
USE [IMDBStaging]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [IMDBStaging]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [IMDBStaging] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
s